### PR TITLE
Encoding tests

### PR DESCRIPTION
**Pull request by lucaspetry**
AlterSubject method updated in CertificateBuilder, so it doesn't take empty strings.
Test classes standardized.
EncodingTest class changed to CertificateBuilderTest and new tests were added.

### CODE REVIEW

**Comment by lucasperin** [comment]
@lucaspetry your commit is conflicting with master. Please merge Master into your branch and resolve conflicts. Once you do it, travis will be able to run the tests for us. If tests pass I will accept your pull request.

**Comment by lucaspetry** [comment]
@lucasperin just did it!

**Comment by lucasperin** [comment]
@lucaspetry again, something went wrong and the branch is conflicting.
I cannot push your commits if travis can't test it.

**Comment by lucasperin** [comment]
Merged branch from @montezano.

**Pull request closed without merging**
